/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  docs: [
    'getting-started',
    'blueprint',
    {
      type: 'category',
      label: '组件',
      collapsed: false,
      items: [
        'components/text',
        'components/image',
        'components/line',
        'components/qrcode',
        'components/block'
      ]
    },
    {
      type: 'category',
      label: '示例',
      collapsed: false,
      items: [
        'examples/choujiang'
      ]
    }
  ]
};
